---

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  listen: remount music share

- name: Remount
  ansible.posix.mount:
    path: "{{ smb_mount_target_dir }}"
    state: remounted
  listen: remount music share
